# TCL File Generated by Component Editor 13.1
# Fri Sep 11 13:11:14 EDT 2015
# DO NOT MODIFY


# 
# cpu_checkpoint_irq "cpu_checkpoint_irq" v1.0
#  2015.09.11.13:11:14
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module cpu_checkpoint_irq
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpu_checkpoint_irq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cpu_checkpoint_irq
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cpu_checkpoint_irq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file cpu_checkpoint_irq.v VERILOG PATH ../../src/cpu_checkpoint_irq.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point checkpoint
# 
add_interface checkpoint avalon end
set_interface_property checkpoint addressUnits WORDS
set_interface_property checkpoint associatedClock clock
set_interface_property checkpoint associatedReset reset
set_interface_property checkpoint bitsPerSymbol 8
set_interface_property checkpoint burstOnBurstBoundariesOnly false
set_interface_property checkpoint burstcountUnits WORDS
set_interface_property checkpoint explicitAddressSpan 0
set_interface_property checkpoint holdTime 0
set_interface_property checkpoint linewrapBursts false
set_interface_property checkpoint maximumPendingReadTransactions 0
set_interface_property checkpoint readLatency 0
set_interface_property checkpoint readWaitTime 1
set_interface_property checkpoint setupTime 0
set_interface_property checkpoint timingUnits Cycles
set_interface_property checkpoint writeWaitTime 0
set_interface_property checkpoint ENABLED true
set_interface_property checkpoint EXPORT_OF ""
set_interface_property checkpoint PORT_NAME_MAP ""
set_interface_property checkpoint CMSIS_SVD_VARIABLES ""
set_interface_property checkpoint SVD_ADDRESS_GROUP ""

add_interface_port checkpoint avs_write write Input 1
add_interface_port checkpoint avs_writedata writedata Input 32
add_interface_port checkpoint avs_read read Input 1
add_interface_port checkpoint avs_readdata readdata Output 32
add_interface_port checkpoint avs_address address Input 8
set_interface_assignment checkpoint embeddedsw.configuration.isFlash 0
set_interface_assignment checkpoint embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment checkpoint embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment checkpoint embeddedsw.configuration.isPrintableDevice 0


# 
# connection point checkpoint_irq
# 
add_interface checkpoint_irq interrupt end
set_interface_property checkpoint_irq associatedAddressablePoint checkpoint
set_interface_property checkpoint_irq associatedClock clock
set_interface_property checkpoint_irq associatedReset reset
set_interface_property checkpoint_irq ENABLED true
set_interface_property checkpoint_irq EXPORT_OF ""
set_interface_property checkpoint_irq PORT_NAME_MAP ""
set_interface_property checkpoint_irq CMSIS_SVD_VARIABLES ""
set_interface_property checkpoint_irq SVD_ADDRESS_GROUP ""

add_interface_port checkpoint_irq checkpoint_irq irq Output 1

