onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -label {clk} /tb_comp_registers/clk
add wave -noupdate -label {reset} /tb_comp_registers/reset
add wave -noupdate -divider tb
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/csr_logical_core_id
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/csr_task_id
add wave -noupdate -group {tb} /tb_comp_registers/csr_pointer_start_write
add wave -noupdate -group {tb} /tb_comp_registers/csr_pointer_end_write
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/csr_pointer_data
add wave -noupdate -group {tb} /tb_comp_registers/comp_pointer_ack
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/fprint_logical_core_id
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/fprint_task_id
add wave -noupdate -group {tb} /tb_comp_registers/fprint_inc_head_pointer
add wave -noupdate -group {tb} /tb_comp_registers/comp_inc_head_pointer_ack
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/fprint_head_pointer
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/comp_tail_pointer_0
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/comp_tail_pointer_1
add wave -noupdate -group {tb} -radix unsigned /tb_comp_registers/comp_tail_pointer_2
add wave -noupdate -group {tb} /tb_comp_registers/comparator_task_id
add wave -noupdate -group {tb} /tb_comp_registers/comparator_inc_tail_pointer
add wave -noupdate -group {tb} /tb_comp_registers/comp_inc_tail_pointer_ack
add wave -noupdate -group {tb} /tb_comp_registers/comparator_reset_task
add wave -noupdate -group {tb} /tb_comp_registers/comp_reset_task_ack
add wave -noupdate -group {tb} /tb_comp_registers/init_complete
add wave -noupdate -group {tb} /tb_comp_registers/i
add wave -noupdate -group {tb} /tb_comp_registers/j
add wave -noupdate -group {tb} /tb_comp_registers/k
add wave -noupdate -divider comp_registers
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/idle
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_pointer_start_write
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_pointer_end_write
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_comp_pointer_ack
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_inc_head_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_comp_inc_head_pointer_ack
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_inc_tail_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_comp_inc_tail_pointer_ack
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_reset_task
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/st_comp_reset_task_ack
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/clk
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/reset
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/csr_logical_core_id
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/csr_task_id
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/csr_pointer_start_write
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/csr_pointer_end_write
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/csr_pointer_data
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comp_pointer_ack
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_logical_core_id
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_task_id
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/fprint_inc_head_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comp_inc_head_pointer_ack
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_head_pointer
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/comp_tail_pointer_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/comp_tail_pointer_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/comp_tail_pointer_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/comparator_task_id
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comparator_inc_tail_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comp_inc_tail_pointer_ack
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comparator_reset_task
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/comp_reset_task_ack
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/start_pointer_mem_0[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_0[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/start_pointer_mem_0[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_0[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/start_pointer_mem_0
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/start_pointer_mem_1[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_1[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/start_pointer_mem_1[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_1[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/start_pointer_mem_1
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/start_pointer_mem_2[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/start_pointer_mem_2[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/start_pointer_mem_2[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/start_pointer_mem_2[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/start_pointer_mem_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_mem_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_mem_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_mem_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_ex_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_ex_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_ex_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_ex_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_ex_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_ex_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_comp_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_comp_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/start_pointer_comp_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_comp_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_comp_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/end_pointer_comp_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/head_pointer_mem_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/head_pointer_mem_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/head_pointer_mem_2
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/tail_pointer_mem_0[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/tail_pointer_mem_0[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_0[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/tail_pointer_mem_0
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/tail_pointer_mem_1[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/tail_pointer_mem_1[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_1[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/tail_pointer_mem_1
add wave -noupdate -group {comp_registers} -radix unsigned -childformat {{{/tb_comp_registers/comp_registers/tail_pointer_mem_2[15]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[14]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[13]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[12]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[11]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[10]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[9]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[8]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[7]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[6]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[5]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[4]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[3]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[2]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[1]} -radix unsigned} {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[0]} -radix unsigned}} -subitemconfig {{/tb_comp_registers/comp_registers/tail_pointer_mem_2[15]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[14]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[13]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[12]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[11]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[10]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[9]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[8]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[7]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[6]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[5]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[4]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[3]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[2]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[1]} {-height 15 -radix unsigned} {/tb_comp_registers/comp_registers/tail_pointer_mem_2[0]} {-height 15 -radix unsigned}} /tb_comp_registers/comp_registers/tail_pointer_mem_2
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_head_pointer_0
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_head_pointer_1
add wave -noupdate -group {comp_registers} -radix unsigned /tb_comp_registers/comp_registers/fprint_head_pointer_2
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/state
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/pointer_start_write
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/pointer_end_write
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/inc_head_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/inc_tail_pointer
add wave -noupdate -group {comp_registers} /tb_comp_registers/comp_registers/reset_task
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {91381 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 386
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {96290 ps}
