# TCL File Generated by Component Editor 13.1
# Wed Mar 04 19:25:08 EST 2015
# DO NOT MODIFY


# 
# utlb "uTLB" v4.2
# Bryan Gingras 2015.03.04.19:25:08
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module utlb
# 
set_module_property DESCRIPTION ""
set_module_property NAME utlb
set_module_property VERSION 4.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Bryan Gingras"
set_module_property DISPLAY_NAME uTLB
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fulltlb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file single_port_ram.v VERILOG PATH ../../src/single_port_ram.v
add_fileset_file fulltlb.sv SYSTEM_VERILOG PATH ../../src/fulltlb.sv


# 
# parameters
# 
add_parameter tagwidth INTEGER 20
set_parameter_property tagwidth DEFAULT_VALUE 20
set_parameter_property tagwidth DISPLAY_NAME tagwidth
set_parameter_property tagwidth TYPE INTEGER
set_parameter_property tagwidth UNITS None
set_parameter_property tagwidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property tagwidth HDL_PARAMETER true
add_parameter addresswidth INTEGER 26 ""
set_parameter_property addresswidth DEFAULT_VALUE 26
set_parameter_property addresswidth DISPLAY_NAME addresswidth
set_parameter_property addresswidth TYPE INTEGER
set_parameter_property addresswidth UNITS None
set_parameter_property addresswidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property addresswidth DESCRIPTION ""
set_parameter_property addresswidth HDL_PARAMETER true
add_parameter numentries INTEGER 32
set_parameter_property numentries DEFAULT_VALUE 32
set_parameter_property numentries DISPLAY_NAME numentries
set_parameter_property numentries TYPE INTEGER
set_parameter_property numentries UNITS None
set_parameter_property numentries ALLOWED_RANGES -2147483648:2147483647
set_parameter_property numentries HDL_PARAMETER true
add_parameter datawidth INTEGER 32
set_parameter_property datawidth DEFAULT_VALUE 32
set_parameter_property datawidth DISPLAY_NAME datawidth
set_parameter_property datawidth TYPE INTEGER
set_parameter_property datawidth UNITS None
set_parameter_property datawidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property datawidth HDL_PARAMETER true
add_parameter byteenablewidth INTEGER 4
set_parameter_property byteenablewidth DEFAULT_VALUE 4
set_parameter_property byteenablewidth DISPLAY_NAME byteenablewidth
set_parameter_property byteenablewidth TYPE INTEGER
set_parameter_property byteenablewidth UNITS None
set_parameter_property byteenablewidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property byteenablewidth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ctrl_reg
# 
add_interface ctrl_reg avalon end
set_interface_property ctrl_reg addressUnits WORDS
set_interface_property ctrl_reg associatedClock clock
set_interface_property ctrl_reg associatedReset reset
set_interface_property ctrl_reg bitsPerSymbol 8
set_interface_property ctrl_reg burstOnBurstBoundariesOnly false
set_interface_property ctrl_reg burstcountUnits WORDS
set_interface_property ctrl_reg explicitAddressSpan 0
set_interface_property ctrl_reg holdTime 0
set_interface_property ctrl_reg linewrapBursts false
set_interface_property ctrl_reg maximumPendingReadTransactions 0
set_interface_property ctrl_reg readLatency 0
set_interface_property ctrl_reg readWaitTime 1
set_interface_property ctrl_reg setupTime 0
set_interface_property ctrl_reg timingUnits Cycles
set_interface_property ctrl_reg writeWaitTime 0
set_interface_property ctrl_reg ENABLED true
set_interface_property ctrl_reg EXPORT_OF ""
set_interface_property ctrl_reg PORT_NAME_MAP ""
set_interface_property ctrl_reg CMSIS_SVD_VARIABLES ""
set_interface_property ctrl_reg SVD_ADDRESS_GROUP ""

add_interface_port ctrl_reg avs_ctrl_reg_address address Input 8
add_interface_port ctrl_reg avs_ctrl_reg_writedata writedata Input 32
add_interface_port ctrl_reg avs_ctrl_reg_write write Input 1
add_interface_port ctrl_reg avs_ctrl_reg_read read Input 1
add_interface_port ctrl_reg avs_ctrl_reg_readdata readdata Output 32
add_interface_port ctrl_reg avs_ctrl_reg_waitrequest waitrequest Output 1
set_interface_assignment ctrl_reg embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl_reg embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl_reg embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl_reg embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avm_byteenable byteenable Output byteenablewidth
add_interface_port avalon_master avm_read read Output 1
add_interface_port avalon_master avm_write write Output 1
add_interface_port avalon_master avm_writedata writedata Output datawidth
add_interface_port avalon_master avm_waitrequest waitrequest Input 1
add_interface_port avalon_master avm_readdata readdata Input datawidth
add_interface_port avalon_master avm_address address Output addresswidth


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgesToMaster avalon_master
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_address address Input addresswidth
add_interface_port avalon_slave avs_byteenable byteenable Input byteenablewidth
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_writedata writedata Input datawidth
add_interface_port avalon_slave avs_waitrequest waitrequest Output 1
add_interface_port avalon_slave avs_readdata readdata Output datawidth
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit avs_address_conduit address Input addresswidth


# 
# connection point fprint
# 
add_interface fprint conduit end
set_interface_property fprint associatedClock clock
set_interface_property fprint associatedReset reset
set_interface_property fprint ENABLED true
set_interface_property fprint EXPORT_OF ""
set_interface_property fprint PORT_NAME_MAP ""
set_interface_property fprint CMSIS_SVD_VARIABLES ""
set_interface_property fprint SVD_ADDRESS_GROUP ""

add_interface_port fprint fprint_waitrequest export Output 1
add_interface_port fprint fprint_data_address export Output addresswidth
add_interface_port fprint fprint_writedata export Output datawidth
add_interface_port fprint fprint_write export Output 1

