# TCL File Generated by Component Editor 13.1
# Thu Jul 10 12:20:21 EDT 2014
# DO NOT MODIFY


# 
# monitor_fifo "monitor_fifo" v1.0
#  2014.07.10.12:20:21
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module monitor_fifo
# 
set_module_property DESCRIPTION ""
set_module_property NAME monitor_fifo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME monitor_fifo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL monitor_fifo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file monitor_fifo.v VERILOG PATH ../../src/monitor_fifo.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file monitor_fifo.v VERILOG PATH ../../src/monitor_fifo.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDRESS_WIDTH INTEGER 10
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 10
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter CSR_ADDRESS_WIDTH INTEGER 5
set_parameter_property CSR_ADDRESS_WIDTH DEFAULT_VALUE 5
set_parameter_property CSR_ADDRESS_WIDTH DISPLAY_NAME CSR_ADDRESS_WIDTH
set_parameter_property CSR_ADDRESS_WIDTH TYPE INTEGER
set_parameter_property CSR_ADDRESS_WIDTH UNITS None
set_parameter_property CSR_ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDRESS_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 64
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 64
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter ALMOST_OVERFLOW INTEGER 56
set_parameter_property ALMOST_OVERFLOW DEFAULT_VALUE 56
set_parameter_property ALMOST_OVERFLOW DISPLAY_NAME ALMOST_OVERFLOW
set_parameter_property ALMOST_OVERFLOW TYPE INTEGER
set_parameter_property ALMOST_OVERFLOW UNITS None
set_parameter_property ALMOST_OVERFLOW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ALMOST_OVERFLOW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point in
# 
add_interface in avalon end
set_interface_property in addressUnits WORDS
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset
set_interface_property in bitsPerSymbol 8
set_interface_property in burstOnBurstBoundariesOnly false
set_interface_property in burstcountUnits WORDS
set_interface_property in explicitAddressSpan 0
set_interface_property in holdTime 0
set_interface_property in linewrapBursts false
set_interface_property in maximumPendingReadTransactions 0
set_interface_property in readLatency 0
set_interface_property in readWaitTime 1
set_interface_property in setupTime 0
set_interface_property in timingUnits Cycles
set_interface_property in writeWaitTime 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in avs_in_write write Input 1
add_interface_port in avs_in_address address Input ADDRESS_WIDTH
add_interface_port in avs_in_waitrequest waitrequest Output 1
add_interface_port in avs_in_writedata writedata Input DATA_WIDTH
set_interface_assignment in embeddedsw.configuration.isFlash 0
set_interface_assignment in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point out
# 
add_interface out avalon end
set_interface_property out addressUnits WORDS
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out bitsPerSymbol 8
set_interface_property out burstOnBurstBoundariesOnly false
set_interface_property out burstcountUnits WORDS
set_interface_property out explicitAddressSpan 0
set_interface_property out holdTime 0
set_interface_property out linewrapBursts false
set_interface_property out maximumPendingReadTransactions 0
set_interface_property out readLatency 0
set_interface_property out readWaitTime 1
set_interface_property out setupTime 0
set_interface_property out timingUnits Cycles
set_interface_property out writeWaitTime 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out avs_out_readdata readdata Output DATA_WIDTH
add_interface_port out avs_out_read read Input 1
add_interface_port out avs_out_address address Input ADDRESS_WIDTH
add_interface_port out avs_out_waitrequest waitrequest Output 1
set_interface_assignment out embeddedsw.configuration.isFlash 0
set_interface_assignment out embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment out embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment out embeddedsw.configuration.isPrintableDevice 0


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input CSR_ADDRESS_WIDTH
add_interface_port csr csr_readdata readdata Output DATA_WIDTH
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_writedata writedata Input DATA_WIDTH
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 irq export Output 1


# 
# connection point empty
# 
add_interface empty conduit end
set_interface_property empty associatedClock clock
set_interface_property empty associatedReset ""
set_interface_property empty ENABLED true
set_interface_property empty EXPORT_OF ""
set_interface_property empty PORT_NAME_MAP ""
set_interface_property empty CMSIS_SVD_VARIABLES ""
set_interface_property empty SVD_ADDRESS_GROUP ""

add_interface_port empty empty export Output 1

