# TCL File Generated by Component Editor 13.1
# Sat Aug 23 15:53:11 EDT 2014
# DO NOT MODIFY


# 
# Fingerprint "Fingerprint" v1.0
#  2014.08.23.15:53:11
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Fingerprint
# 
set_module_property DESCRIPTION ""
set_module_property NAME Fingerprint
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Fingerprint
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL crc_fingerprint
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file crc_fingerprint.v VERILOG PATH ../../src/crc_fingerprint.v TOP_LEVEL_FILE
add_fileset_file crc_counter.v VERILOG PATH ../../src/crc_counter.v
add_fileset_file crc_fsm_rtla.v VERILOG PATH ../../src/crc_fsm_rtla.v
add_fileset_file crc_rtla.v VERILOG PATH ../../src/crc_rtla.v
add_fileset_file crc_sb_fsm.v VERILOG PATH ../../src/crc_sb_fsm.v
add_fileset_file crc_store_buffer.v VERILOG PATH ../../src/crc_store_buffer.v
add_fileset_file fifo.v VERILOG PATH ../../src/fifo.v
add_fileset_file crc_pause.v VERILOG PATH ../../src/crc_pause.v
add_fileset_file lifo.v VERILOG PATH ../../src/lifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL crc_fingerprint
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file crc_fingerprint.v VERILOG PATH ../../src/crc_fingerprint.v
add_fileset_file crc_counter.v VERILOG PATH ../../src/crc_counter.v
add_fileset_file crc_fsm_rtla.v VERILOG PATH ../../src/crc_fsm_rtla.v
add_fileset_file crc_rtla.v VERILOG PATH ../../src/crc_rtla.v
add_fileset_file crc_sb_fsm.v VERILOG PATH ../../src/crc_sb_fsm.v
add_fileset_file crc_store_buffer.v VERILOG PATH ../../src/crc_store_buffer.v
add_fileset_file fifo.v VERILOG PATH ../../src/fifo.v
add_fileset_file crc_pause.v VERILOG PATH ../../src/crc_pause.v
add_fileset_file lifo.v VERILOG PATH ../../src/lifo.v


# 
# parameters
# 
add_parameter CORE_ID INTEGER 0
set_parameter_property CORE_ID DEFAULT_VALUE 0
set_parameter_property CORE_ID DISPLAY_NAME CORE_ID
set_parameter_property CORE_ID TYPE INTEGER
set_parameter_property CORE_ID UNITS None
set_parameter_property CORE_ID ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CORE_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits SYMBOLS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 slave_spr_addr address Input 8
add_interface_port avalon_slave_0 slave_spr_dat_i writedata Input 32
add_interface_port avalon_slave_0 slave_spr_dat_o readdata Output 32
add_interface_port avalon_slave_0 slave_spr_read read Input 1
add_interface_port avalon_slave_0 slave_spr_write write Input 1
add_interface_port avalon_slave_0 slave_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 27
add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output 32
add_interface_port avalon_master master_read read Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point fprint_conduit
# 
add_interface fprint_conduit conduit end
set_interface_property fprint_conduit associatedClock clock
set_interface_property fprint_conduit associatedReset reset_sink
set_interface_property fprint_conduit ENABLED true
set_interface_property fprint_conduit EXPORT_OF ""
set_interface_property fprint_conduit PORT_NAME_MAP ""
set_interface_property fprint_conduit CMSIS_SVD_VARIABLES ""
set_interface_property fprint_conduit SVD_ADDRESS_GROUP ""

add_interface_port fprint_conduit waitrequest export Input 1
add_interface_port fprint_conduit data_address export Input 27
add_interface_port fprint_conduit writedata export Input 32
add_interface_port fprint_conduit write export Input 1

