% Autogenerated file: Sun Mar 22 13:54:14 2015
function writeCodeInfoFcn


% Load a ComponentInterface object from IR
codeIRInfoStruct = load('/Users/anthonydelage/Documents/MATLAB/TransmissionControl_ert_rtw/tlc/codeIRInfo.mat');
codeInfo = codeIRInfoStruct.codeInfo;


          
% Built-In Type: 1
Type_1_R0_V0 = numerictype('single');
  Type_1_R0_V0.Name = 'single';
  Type_1_R0_V0.Identifier = 'real32_T';
  Type_1_R0_V0.ReadOnly   = 0;
  Type_1_R0_V0.Volatile   = 0;
        
% Variable: Var_fluid_sensor
Var_fluid_sensor = RTW.Variable(Type_1_R0_V0, 'fluid_sensor');
    Var_fluid_sensor.Owner           = '';
    Var_fluid_sensor.DeclarationFile = '';
    
        Var_fluid_sensor.StorageSpecifier = 'extern';
        
    % Setting Inport#1's implementation    
    codeInfo.Inports(1).Implementation = Var_fluid_sensor;

          
% Built-In Type: 8
 Type_8_R0_V0 = numerictype('boolean');
  Type_8_R0_V0.Name = 'boolean';
  Type_8_R0_V0.Identifier = 'boolean_T';
  Type_8_R0_V0.ReadOnly   = 0;
  Type_8_R0_V0.Volatile   = 0;
            
    
% Variable: Var_warning_light
Var_warning_light = RTW.Variable(Type_8_R0_V0, 'warning_light');
    Var_warning_light.Owner           = '';
    Var_warning_light.DeclarationFile = '';
    
        Var_warning_light.StorageSpecifier = 'extern';
        
    % Setting Outport#1's Implementation    
    codeInfo.Outports(1).Implementation = Var_warning_light;

skippedParameters = [];
      
% Matrix Type
Type_18_R0_V0 = embedded.matrixtype;
  Type_18_R0_V0.BaseType   = Type_1_R0_V0;
  Type_18_R0_V0.Dimensions = [1, 1];
    
  tmpParams = [];
if ~isempty(tmpParams)
codeInfo.Parameters = [codeInfo.Parameters; tmpParams];
end

    tmpArgs         = [];
tmpActualArgs   = [];
tmpRet          = [];
tmpActualReturn = [];
  

  Initialize_Prototype = RTW.CImplementation;
  Initialize_Prototype.Arguments  = tmpArgs;
  Initialize_Prototype.Return     = tmpRet;
  Initialize_Prototype.HeaderFile = ['TransmissionControl', '.h'];
  Initialize_Prototype.SourceFile = ['TransmissionControl', '.c'];

  Initialize_Interface = RTW.FunctionInterface;
  Initialize_Interface.Prototype    = Initialize_Prototype;
  Initialize_Interface.ActualArgs   = tmpActualArgs;
  Initialize_Interface.ActualReturn = tmpActualReturn;

      Initialize_Prototype.Name = 'TransmissionControl_initialize';
  time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
      Initialize_Interface.Timing = time_constant;
      codeInfo.InitializeFunctions =  [codeInfo.InitializeFunctions; Initialize_Interface'];

          tmpArgs         = [];
tmpActualArgs   = [];
tmpRet          = [];
tmpActualReturn = [];
  

  OutputUpdate_Prototype = RTW.CImplementation;
  OutputUpdate_Prototype.Arguments  = tmpArgs;
  OutputUpdate_Prototype.Return     = tmpRet;
  OutputUpdate_Prototype.HeaderFile = ['TransmissionControl', '.h'];
  OutputUpdate_Prototype.SourceFile = ['TransmissionControl', '.c'];

  OutputUpdate_Interface = RTW.FunctionInterface;
  OutputUpdate_Interface.Prototype    = OutputUpdate_Prototype;
  OutputUpdate_Interface.ActualArgs   = tmpActualArgs;
  OutputUpdate_Interface.ActualReturn = tmpActualReturn;

      OutputUpdate_Prototype.Name = 'TransmissionControl_step';
  time_0 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 0));
      OutputUpdate_Interface.Timing = time_0;
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions; OutputUpdate_Interface'];

      tmpArgs         = [];
tmpActualArgs   = [];
tmpRet          = [];
tmpActualReturn = [];
  

  Terminate_Prototype = RTW.CImplementation;
  Terminate_Prototype.Arguments  = tmpArgs;
  Terminate_Prototype.Return     = tmpRet;
  Terminate_Prototype.HeaderFile = ['TransmissionControl', '.h'];
  Terminate_Prototype.SourceFile = ['TransmissionControl', '.c'];

  Terminate_Interface = RTW.FunctionInterface;
  Terminate_Interface.Prototype    = Terminate_Prototype;
  Terminate_Interface.ActualArgs   = tmpActualArgs;
  Terminate_Interface.ActualReturn = tmpActualReturn;

  time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
      Terminate_Interface.Timing = time_constant;
      Terminate_Prototype.Name = [codeInfo.Name, '_terminate'];
      codeInfo.TerminateFunctions =  [codeInfo.TerminateFunctions; Terminate_Interface'];



if ~isempty(skippedParameters)
codeInfo.Parameters(skippedParameters) = [];
end


% Handling Right-Click Builds
ss = rtwprivate('getSourceSubsystemHandle',codeInfo.GraphicalPath);
% Check if Rt-Click build, then re-map SIDs
if ~isempty(ss) && rtwprivate('rtwattic','hasSIDMap')
   codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo);
end

  if exist('expInports', 'var')
      save codeInfo.mat codeInfo expInports ;
  else
      save codeInfo.mat codeInfo ;
  end
returnVal = 1;

% End Function: writeCodeInfoFcn

function idx = getIndexFromTimingInternalId(internalIdVec, internalId)
 idx = find(internalIdVec == internalId);
 if (isempty(idx) || (length(idx) > 1))
    ciMsg = 'Time object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getIndexFromTimingInternalId

function checkDataGraphicalNames(ciName, rtwName)
  if (strcmp(ciName, rtwName) ~= 1)
    ciMsg = ['Name mismatch: ', ciName, ' and ', rtwName]; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: checkDataGraphicalNames

function iData = getInternalDataByName(iDataVec, iDataName)
 iData = find(iDataVec, 'GraphicalName', iDataName);
 if (isempty(iData) || (length(iData) > 1))
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByName

function iData = getInternalDataByVariableName(iDataVec, iDataVariableName)
 iData = [];
 for idxData = 1:numel(iDataVec)
    if strcmp(iDataVariableName, iDataVec(idxData).Implementation.VariableName)
       iData = iDataVec(idxData);
       break
    end
 end
 if isempty(iData)
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByVariableName

function codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo)
    
% Extract Subsystem Build Map from AtticData
    Subsystem_Build_Mapping = rtwprivate('rtwattic','getSIDMap');

% Parameters
    for i = 1:length(codeInfo.Parameters)
        sid = codeInfo.Parameters(i).SID;        

        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Parameters(i).SID = sid;        
    end
    
% Data Stores
     for i = 1:length(codeInfo.DataStores)
         sid = codeInfo.DataStores(i).SID;         

         sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
         codeInfo.DataStores(i).SID = sid;
     end
    
% Inports
    for i = 1:length(codeInfo.Inports)
        sid = codeInfo.Inports(i).SID;
        
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Inports(i).SID = sid;
    end
    
% Outports
    for i = 1:length(codeInfo.Outports)
        sid = codeInfo.Outports(i).SID;
 
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Outports(i).SID = sid;
    end    
   
